export type notesInfoTypes = {
  NOTES_LIST_REQUEST: 'NOTES_LIST_REQUEST';
  NOTES_LIST_SUCCESS: 'NOTES_LIST_SUCCESS';
  NOTES_LIST_FAIL: 'NOTES_LIST_FAIL';

  NOTES_CREATE_REQUEST: 'NOTES_CREATE_REQUEST';
  NOTES_CREATE_SUCCESS: 'NOTES_CREATE_SUCCESS';
  NOTES_CREATE_FAIL: 'NOTES_CREATE_FAIL';

  NOTES_UPDATE_REQUEST: 'NOTES_UPDATE_REQUEST';
  NOTES_UPDATE_SUCCESS: 'NOTES_UPDATE_SUCCESS';
  NOTES_UPDATE_FAIL: 'NOTES_UPDATE_FAIL';

  NOTES_DELETE_REQUEST: 'NOTES_DELETE_REQUEST';
  NOTES_DELETE_SUCCESS: 'NOTES_DELETE_SUCCESS';
  NOTES_DELETE_FAIL: 'NOTES_DELETE_FAIL';
};
